name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        registry-url: ['https://registry.npmjs.org']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ matrix.registry-url }}
      - name: 'Installing node-gyp'
        run: npm i -g node-gyp
      - name: 'Build'
        run: node-gyp rebuild
      - name: 'Copy build output to package directory'
        run: |
          mkdir -p dist
          cp build/Release/*.node dist/
      - name: 'Package'
        run: npm pack
      - name: 'Publish'
        run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
